name: EventSpigot
version: 0.0.1
description: EventSpigot
main: dev.imabad.mceventsuite.spigot.EventSpigot
author: Rushmead
api-version: 1.16
softdepend: [Vault, PlotSquared, Citizens]
depend: [WorldEdit]
load: STARTUP
